export const ADD_INGREDIENT: "ADD_INGREDIENT" = "ADD_INGREDIENT";
export const ADD_BUN: "ADD_BUN" = "ADD_BUN";
export const REMOVE_INGREDIENT: "REMOVE_INGREDIENT" = "REMOVE_INGREDIENT";
export const SORT_TOPPING: "SORT_TOPPING" = "SORT_TOPPING";
export const CLEAR_BURGER: "CLEAR_BURGER" = "CLEAR_BURGER";
