export const WS_FEED_CONNECT: "WS_FEED_CONNECT" = "WS_FEED_CONNECT";
export const WS_FEED_ERROR: "WS_FEED_ERROR" = "WS_FEED_ERROR";
export const WS_FEED_CLOSE: "WS_FEED_CLOSE" = "WS_FEED_CLOSE";
export const WS_FEED_GET_MESSAGE: "WS_FEED_GET_MESSAGE" = "WS_FEED_GET_MESSAGE";
export const WS_FEED_SEND_MESSAGE: "WS_FEED_SEND_MESSAGE" =
    "WS_FEED_SEND_MESSAGE";
