export const WS_USER_FEED_CONNECT: "WS_USER_FEED_CONNECT" =
    "WS_USER_FEED_CONNECT";
export const WS_USER_FEED_ERROR: "WS_USER_FEED_ERROR" = "WS_USER_FEED_ERROR";
export const WS_USER_FEED_CLOSE: "WS_USER_FEED_CLOSE" = "WS_USER_FEED_CLOSE";
export const WS_USER_FEED_GET_MESSAGE: "WS_USER_FEED_GET_MESSAGE" =
    "WS_USER_FEED_GET_MESSAGE";
